spring:
  application:
    name: rrhh
  jpa:
    hibernate:
      ddl-auto: none
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
#    username: ${POSTGRES_USER}
#    password: ${POSTGRES_PASSWORD}

---
spring:
  profiles: local, test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    #;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

server:
  port: 8888

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
