spring:
  application:
    name: rrhh
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${MYSQL_DB}
#    username: ${MYSQL_USER}
#    password: ${MYSQL_PASSWORD}

server:
  port: 8080

---
spring:
  profiles: local, test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
