CREATE TABLE COUNTRIES
 (
 COUNTRY_ID CHAR (2 BYTE) NOT NULL,
 COUNTRY_NAME VARCHAR2 (40 BYTE) ,
 REGION_ID NUMBER,
 CONSTRAINT countries_pk PRIMARY KEY (COUNTRY_ID)
 )  ;


CREATE TABLE DEPARTMENTS
 (
 DEPARTMENT_ID NUMBER (4) NOT NULL AUTO_INCREMENT,
 DEPARTMENT_NAME VARCHAR2 (30 BYTE) NOT NULL ,
 MANAGER_ID NUMBER (6) ,
 LOCATION_ID NUMBER (4),
 CONSTRAINT departments_pk PRIMARY KEY (DEPARTMENT_ID)
 ) ;

CREATE TABLE EMPLOYEES
 (
 EMPLOYEE_ID NUMBER (6) NOT NULL AUTO_INCREMENT,
 FIRST_NAME VARCHAR2 (20 BYTE) ,
 LAST_NAME VARCHAR2 (25 BYTE) NOT NULL ,
 EMAIL VARCHAR2 (25 BYTE) NOT NULL ,
 PHONE_NUMBER VARCHAR2 (20 BYTE) ,
 HIRE_DATE DATE NOT NULL ,
 JOB_ID VARCHAR2 (10 BYTE) NOT NULL ,
 SALARY NUMBER (8,2) ,
 COMMISSION_PCT NUMBER (5,2) ,
 MANAGER_ID NUMBER (6) ,
 DEPARTMENT_ID NUMBER (4),
 CONSTRAINT employees_pk PRIMARY KEY (EMPLOYEE_ID)
 ) ;

CREATE TABLE JOBS
 (
 JOB_ID VARCHAR2 (10 BYTE) NOT NULL ,
 JOB_TITLE VARCHAR2 (35 BYTE) NOT NULL ,
 MIN_SALARY NUMBER (6) ,
 MAX_SALARY NUMBER (6),
 CONSTRAINT jobs_pk PRIMARY KEY (JOB_ID)
 ) ;

CREATE TABLE JOB_HISTORY
 (
 EMPLOYEE_ID NUMBER (6) NOT NULL ,
 START_DATE DATE NOT NULL ,
 END_DATE DATE NOT NULL ,
 JOB_ID VARCHAR2 (10 BYTE) NOT NULL ,
 DEPARTMENT_ID NUMBER (4)
 ) ;

CREATE TABLE LOCATIONS
 (
 LOCATION_ID NUMBER (4) NOT NULL AUTO_INCREMENT,
 STREET_ADDRESS VARCHAR2 (40 BYTE) ,
 POSTAL_CODE VARCHAR2 (12 BYTE) ,
 CITY VARCHAR2 (30 BYTE) NOT NULL ,
 STATE_PROVINCE VARCHAR2 (25 BYTE) ,
 COUNTRY_ID CHAR (2 BYTE),
 CONSTRAINT locations_pk PRIMARY KEY (LOCATION_ID)
 ) ;

CREATE TABLE REGIONS
 (
 REGION_ID NUMBER NOT NULL AUTO_INCREMENT,
 REGION_NAME VARCHAR2 (25 BYTE),
 CONSTRAINT regions_pk PRIMARY KEY (REGION_ID)
 ) ;
